version: "3"
services:
  my-own-mysql:
    image: mysql:8.0
    container_name: my-own-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqlDBData:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  my-own-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-own-phpmyadmin
    links:
      - 'my-own-mysql:db'
    ports:
      - '8081:80'

volumes:
  mysqlDBData:


## Use root/example as user/password credentials
#version: '3.1'
#
#services:
#
#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=example
#      - MYSQL_USER=root
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080