#auth0:
#  audience: http://localhost:9095/products
new_config:
  token: akash
server:
  port: '9095'
spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-j8ajv706.us.auth0.com/
  data:
    mongodb:
      uri: mongodb+srv://root:root@yantracloudappcluster.gn3di.mongodb.net/yantraCloudAppDB?retryWrites=true&w=majority
token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNDR2pKMmVhM09DTG5uSWpIRm5GcCJ9.eyJpc3MiOiJodHRwczovL2Rldi1qOGFqdjcwNi51cy5hdXRoMC5jb20vIiwic3ViIjoiRW9qSGI2dHVDdXkxMnVUdlVJZjB6TTUzV0ZTeGR3TEZAY2xpZW50cyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTA5NS9wcm9kdWN0cyIsImlhdCI6MTY0MTcyNDQyNCwiZXhwIjoxNjQxODEwODI0LCJhenAiOiJFb2pIYjZ0dUN1eTEydVR2VUlmMHpNNTNXRlN4ZHdMRiIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.f7BIsx63BMLdIxalrX0VsGEkryU40Mf75qK1GDET5TkOqbZN7ZDz2CsTbwmc6wE0cu70ONLWmePEeXgGefv0Mt8xJg05vRycY-P1np-2ULhRQmj2IvRc7pkIG09xQ1RFujOPg8DN5zLw7-0mNkjNQ5oKQiJxO6SVP_npFBokyagd2qUCVyBM6g4DVJl_r7-NRyxSHAxlzy8wwS52SmbjJeLnmCq-WPMkKOT2odulPN9d39NaLrnGynPq6vX5YIC1kfsllOLhyinEARos_GzBPOIBlTsHkACfs6oOSTk9M-4wD1GwHg-ucxKWwwxWduMq4doiIVNKWixn1KP-p0iQTQ