pipeline {
  agent any

  stages {
      stage('Build Docker Image'){
          steps {
              sh (script: 'docker images -a')
           }
      }
    stage('build') {
      steps {
      withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'password', usernameVariable: 'username')]) {
         sh 'mvn clean install --no-transfer-progress -Djib.to.auth.username=$username -Djib.to.auth.password=$password'
      }

      }
    }

  }
}
