pipeline {
  agent any

  stages {
        stage('Set Up Parameters') {
            script{
            properties([parameters([booleanParam(defaultValue: true, name: 'STAGE_SONAR'), booleanParam(defaultValue: false, name: 'STAGE_DEPLOY')]), pipelineTriggers([githubPush()])])

            }
        }

      stage('Sonar Analysis'){

          steps {
                withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'sonarToken')]) {
                    sh ('mvn verify --no-transfer-progress org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=yantraCloudApp_products-api -Dsonar.login=$sonarToken')
                }

           }
      }
    stage('Build and Generate Docker Image') {
      steps {
      withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'password', usernameVariable: 'username')]) {
//          sh 'mvn clean install --no-transfer-progress -DskipTests -Djib.to.auth.username=$username -Djib.to.auth.password=$password'
          sh 'mvn clean install --no-transfer-progress -Djib.to.auth.username=$username -Djib.to.auth.password=$password'
      }

      }
    }

  }
}
