pipeline {
  agent any

  stages {
      stage('Build Docker Image'){
          steps {
              sh (script: 'docker images -a')
           }
      }
    stage('build') {
      steps {
        sh 'mvn clean install --no-transfer-progress'
      }
    }

  }
}
